# Generated by Django 3.2.16 on 2023-09-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='payments',
            field=models.ManyToManyField(blank=True, to='payment.Payment'),
        ),
    ]
